In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv("estadisticas_equipo.csv")
df

,nombre,partido,titular,suplente,Goles,Asist,posicion,golXpart,asistXpart,contribucion_gol,pct_partidos_jugados,pct_titularidad
0,Jorge Rodriguez,25,17,8,0,0,Port,0.00,0.00,0.00,83.3,68.0
1,Javier Sanchez,27,14,13,0,0,Port,0.00,0.00,0.00,90.0,51.9
2,Manuel Hermoso,25,19,6,0,0,Cent,0.00,0.00,0.00,83.3,76.0
3,Martin Peiro,22,6,16,0,0,Cent,0.00,0.00,0.00,73.3,27.3
4,Miguel Gutierrez,29,28,1,7,2,Cent,0.24,0.07,0.31,96.7,96.6
5,Kosta Velazco,25,19,6,5,6,Lat,0.20,0.24,0.44,83.3,76.0
6,Jaime Cerezo,27,24,3,4,7,Lat,0.15,0.26,0.41,90.0,88.9
7,Alejandro Martinez,21,5,16,2,5,Lat,0.10,0.24,0.33,70.0,23.8
8,Pablo Leon,19,14,5,1,3,Lat,0.05,0.16,0.21,63.3,73.7
9,Hugo Mauro,25,11,14,1,0,Lat,0.04,0.00,0.04,83.3,44.0
10,Cesar Garcia,26,21,5,3,8,Med,0.12,0.31,0.42,86.7,80.8
11,Alvaro Cano,23,20,3,5,2,Med,0.22,0.09,0.30,76.7,87.0
12,Mario Andres,19,2,17,0,0,Med,0.00,0.00,0.00,63.3,10.5
13,Diego Baptista,30,29,1,15,21,Med,0.50,0.70,1.20,100.0,96.7
14,Alvaro Ruiz,18,11,7,1,2,Med,0.06,0.11,0.17,60.0,61.1
15,Alejandro Galindo,30,26,4,30,7,Del,1.00,0.23,1.23,100.0,86.7
16,Carlos Born,13,3,10,2,0,Del,0.15,0.00,0.15,43.3,23.1
17,Hugo Diaz,20,19,1,19,8,Del,0.95,0.40,1.35,66.7,95.0
18,Sergio Velazco,26,18,8,7,5,Del,0.27,0.19,0.46,86.7,69.2

In [13]:
df["golXpart"] = (df["Goles"] / df["Part"]).round(2)
df["asistXpart"] = (df["Asist"] / df["Part"]).round(2)
df["gol/asistXpart"] = ((df['Goles'] + df['Asist']) / df['Part']).round(2)
df["%Part"] = ((df["Part"] / 30) * 100).round(1)
df["%Titu"] = ((df["Titu"] / df["Part"]) * 100).round(1)
df

KeyError: 'Part'

In [20]:
df = df.rename( columns={
    "Nombre" : "nombre",
    'Partido': 'partido',
    "Titular" : "titular",
    "Suplente" : "suplente",
    "Goles" : "goles",
    "Asist" : "asist",
    "Posicion" : "posicion",
    "golXpart" : "gol_x_part",
    "asistXpart" : "asist_x_part",
    "Contribucion_gol" : "contribucion_gol",
    "%Titularidad" : "pct_titularidad",
    "%Partidos_jugados" : "pct_partidos_jugados"
    })
df

,nombre,partido,titular,suplente,goles,asist,posicion,gol_x_part,asist_x_part,contribucion_gol,pct_partidos_jugados,pct_titularidad
0,Jorge Rodriguez,25,17,8,0,0,Port,0.00,0.00,0.00,83.3,68.0
1,Javier Sanchez,27,14,13,0,0,Port,0.00,0.00,0.00,90.0,51.9
2,Manuel Hermoso,25,19,6,0,0,Cent,0.00,0.00,0.00,83.3,76.0
3,Martin Peiro,22,6,16,0,0,Cent,0.00,0.00,0.00,73.3,27.3
4,Miguel Gutierrez,29,28,1,7,2,Cent,0.24,0.07,0.31,96.7,96.6
5,Kosta Velazco,25,19,6,5,6,Lat,0.20,0.24,0.44,83.3,76.0
6,Jaime Cerezo,27,24,3,4,7,Lat,0.15,0.26,0.41,90.0,88.9
7,Alejandro Martinez,21,5,16,2,5,Lat,0.10,0.24,0.33,70.0,23.8
8,Pablo Leon,19,14,5,1,3,Lat,0.05,0.16,0.21,63.3,73.7
9,Hugo Mauro,25,11,14,1,0,Lat,0.04,0.00,0.04,83.3,44.0
10,Cesar Garcia,26,21,5,3,8,Med,0.12,0.31,0.42,86.7,80.8
11,Alvaro Cano,23,20,3,5,2,Med,0.22,0.09,0.30,76.7,87.0
12,Mario Andres,19,2,17,0,0,Med,0.00,0.00,0.00,63.3,10.5
13,Diego Baptista,30,29,1,15,21,Med,0.50,0.70,1.20,100.0,96.7
14,Alvaro Ruiz,18,11,7,1,2,Med,0.06,0.11,0.17,60.0,61.1
15,Alejandro Galindo,30,26,4,30,7,Del,1.00,0.23,1.23,100.0,86.7
16,Carlos Born,13,3,10,2,0,Del,0.15,0.00,0.15,43.3,23.1
17,Hugo Diaz,20,19,1,19,8,Del,0.95,0.40,1.35,66.7,95.0
18,Sergio Velazco,26,18,8,7,5,Del,0.27,0.19,0.46,86.7,69.2

In [21]:
df.to_csv('estadisticas_equipo.csv', index=False, encoding='utf-8')